using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace FmgLib.MauiMarkup.Generator.Extensions;

/// <summary>
/// Builds the generated extension methods for a given MAUI control or attached property.
/// </summary>
public sealed partial class ExtensionGenerator
{
    readonly Compilation compilation;
    readonly CancellationToken cancellationToken;
    readonly INamedTypeSymbol mainSymbol;
    readonly bool isVisualElement;
    bool isGeneratedExtension = false;
    readonly AttachedModel? attachedModel;
    readonly ISet<INamedTypeSymbol>? generationSet;
    List<string> bindablePropertyNames = new();
    List<string> redefinedProperties = new();
    HashSet<string> skippedProperties = new();

    StringBuilder builder = new();

    public ExtensionGenerator(Compilation compilation, INamedTypeSymbol symbol, CancellationToken cancellationToken)
        : this(compilation, symbol, generationSet: null, cancellationToken)
    {
    }

    public ExtensionGenerator(Compilation compilation, INamedTypeSymbol symbol, ISet<INamedTypeSymbol>? generationSet, CancellationToken cancellationToken)
    {
        this.compilation = compilation;
        this.mainSymbol = symbol;
        this.cancellationToken = cancellationToken;
        this.generationSet = generationSet;
        isVisualElement = Helpers.IsVisualElement(mainSymbol);
    }

    public ExtensionGenerator(Compilation compilation, AttachedModel attachedModel, CancellationToken cancellationToken)
    {
        this.compilation = compilation;
        this.mainSymbol = attachedModel.MainSymbol;
        this.cancellationToken = cancellationToken;
        isVisualElement = Helpers.IsVisualElement(mainSymbol);
        this.attachedModel = attachedModel;
    }

    public (string, string, bool) Build()
    {
        builder.Clear();
        builder.AppendLine("//");
        builder.AppendLine("// <auto-generated-fmglib-mauimarkup-generator />");
        builder.AppendLine("//");
        builder.AppendLine();
        // Generated files are compiled with whatever nullable/warning settings the CONSUMING project
        // happens to use. Two of those settings produce thousands of diagnostics that the consumer
        // can neither fix nor meaningfully act on, so they are pinned per file:
        //   * `#nullable enable annotations` — property types are printed with their nullable
        //     annotations (`string?`), which is CS8669 in a project that leaves nullable disabled.
        //     Enabling only the ANNOTATION context makes the annotations legal without turning on
        //     nullable *warnings* for generated bodies.
        //   * CS0612/CS0618 — a control can expose a property whose TYPE is [Obsolete] (or be
        //     obsolete itself, e.g. MAUI's Frame); the fluent wrapper is not a new usage of it, and
        //     under TreatWarningsAsErrors the warning would break the consumer's build outright.
        builder.AppendLine("#nullable enable annotations");
        builder.AppendLine("#pragma warning disable CS0612, CS0618");
        builder.AppendLine();

        GenerateExtensionNameSpace();

        builder.AppendLine();

        return ($"{mainSymbol.ContainingNamespace.ToDisplayString()}.{Helpers.GetNormalizedFileName(mainSymbol)}{(attachedModel != null ? "Attached" : "")}", builder.ToString(), isGeneratedExtension);
    }

    void GenerateExtensionNameSpace()
    {
        var className = $"{Helpers.GetNormalizedClassName(mainSymbol)}{(attachedModel != null ? "Attached" : "")}Extension";

        builder.Append($@"
namespace FmgLib.MauiMarkup;

public static partial class {className}
{{");

        GenerateClassExtensionBody();

        builder.AppendLine($@"
}}
");
    }

    void GenerateClassExtensionBody()
    {
        cancellationToken.ThrowIfCancellationRequested();

        // Every generated member names the target type in a `where T :` constraint, so an
        // obsolete-as-error control (CS0619) would poison the whole file rather than one method.
        if (Helpers.IsObsoleteAsError(mainSymbol))
        {
            return;
        }

        var editorBrowsableAttribute = compilation.FindNamedType("System.ComponentModel.EditorBrowsableAttribute");
        var bindablePropertyType = compilation.FindNamedType("Microsoft.Maui.Controls.BindableProperty");
        var members = mainSymbol
            .GetMembers()
            .Where(member => SymbolEqualityComparer.Default.Equals(member.ContainingType, mainSymbol))
            .ToArray();

        var propertiesMap = members
            .OfType<IPropertySymbol>()
            .Where(IsEligibleProperty)
            .OrderBy(property => property.Name, StringComparer.Ordinal)
            .ToList();

        ClassifyRedefinedProperties(propertiesMap);

        var fieldsMap = members
            .OfType<IFieldSymbol>()
            .Where(IsEligibleField)
            .ToList();

        bindablePropertyNames = fieldsMap
            .Where(field => field.IsStatic &&
                ((bindablePropertyType != null && SymbolEqualityComparer.Default.Equals(field.Type, bindablePropertyType)) ||
                 field.Type.GetFullyQualifiedName().Equals("Microsoft.Maui.Controls.BindableProperty", StringComparison.Ordinal)))
            .Select(field => field.Name.Replace("PropertyKey", string.Empty).Replace("Property", string.Empty))
            .ToList();

        var properties = propertiesMap
            .Where(property => !skippedProperties.Contains(property.Name))
            .Where(property => IsSetterUsable(property) || bindablePropertyNames.Any(name => name.Equals(property.Name, StringComparison.Ordinal)))
            .ToList();

        var readOnlyListProperties = propertiesMap
            .Where(property => !skippedProperties.Contains(property.Name))
            .Where(property => property.IsReadOnly &&
                !bindablePropertyNames.Any(name => name.Equals(property.Name, StringComparison.InvariantCultureIgnoreCase)) &&
                GetAddableElementType(property) != null)
            .ToList();

        var events = members
           .OfType<IEventSymbol>()
           .Where(@event => @event.DeclaredAccessibility == Accessibility.Public)
           .Where(@event => @event.Name.IndexOf('.') < 0)
           .Where(@event => !HasEditorBrowsable(@event, editorBrowsableAttribute))
           .Where(@event => !HasObsoleteAttribute(@event))
           // Same reasoning as static properties: `self.Event += handler` on a static event is a
           // compile error (CS0176), and a static event is process-wide, not per-instance, state.
           .Where(@event => !@event.IsStatic)
           // The generated handler parameter/lambda action type must itself be public, or every
           // consumer outside this assembly fails to compile against the generated method.
           .Where(@event => Helpers.IsEffectivelyPublic(@event.Type) && !Helpers.IsUnusableType(@event.Type))
           // An unresolvable event type (missing transitive reference) would be printed as a
           // nonexistent type name; and `self.Event += handler` requires the add accessor to be
           // reachable from the generated (consumer-assembly) code — a `public event` declared with
           // a restricted `add` accessor, or inherited from a type the consumer cannot see, is not.
           .Where(@event => @event.Type.TypeKind == TypeKind.Delegate)
           .Where(@event => @event.AddMethod != null && compilation.IsSymbolAccessibleWithin(@event.AddMethod, compilation.Assembly))
           .GroupBy(@event => @event.Name, StringComparer.OrdinalIgnoreCase)
           .Select(group => group.First())
           .OrderBy(@event => @event.Name, StringComparer.Ordinal)
           .ToArray();

        if (attachedModel == null)
        {
            foreach (var prop in readOnlyListProperties)
            {
                cancellationToken.ThrowIfCancellationRequested();
                GenerateExtensionMethod(prop, true);
            }

            foreach (var prop in properties)
            {
                cancellationToken.ThrowIfCancellationRequested();
                GenerateExtensionMethod(prop);
            }

            foreach (var @event in events)
            {
                cancellationToken.ThrowIfCancellationRequested();
                GenerateEventMethod(@event);
            }

            if (CanGenerateITextAlignmentExtensions())
                GenerateExtensionMethods_ITextAlignment(mainSymbol);
        }
        else
        {
            GenerateAttachedExtensionMethod(attachedModel!);
        }
    }

    bool IsEligibleProperty(IPropertySymbol property)
    {
        if (property.DeclaredAccessibility != Accessibility.Public || HasObsoleteAttribute(property))
        {
            return false;
        }

        // Static properties are type-level configuration (e.g. a shared default), not per-instance
        // state — an instance-fluent `new Foo().Bar(value)` extension would silently write to the
        // TYPE, not to `self`, which is misleading API design and, worse, several of the generated
        // shapes (notably Animate…To) hardcode an instance access and would emit `self.Bar = value`
        // for a static member, which fails to compile (CS0176). Skipping statics entirely avoids the
        // whole class of bugs rather than special-casing every generation shape. Setting a static
        // config knob remains a single plain C# statement (`SomeControl.Bar = value;`) that needs no
        // fluent wrapper.
        if (property.IsStatic)
        {
            return false;
        }

        // Ref-returning properties (`ref readonly T Foo => ref field;`) cannot be targeted by a
        // normal `self.Foo = value` assignment.
        if (property.ReturnsByRef || property.ReturnsByRefReadonly)
        {
            return false;
        }

        // A `ref struct` (e.g. Span<T>) property type cannot be used as a generic method parameter
        // or captured in a lambda/local, both of which the generated overloads require.
        if (property.Type.IsRefLikeType)
        {
            return false;
        }

        // A public property whose type (or a generic type argument / array element type) is not
        // itself public cannot appear in a public method signature without breaking every caller
        // outside this assembly (CS0053-class errors). This is an occasional, deliberate or
        // accidental pattern in third-party libraries; skip rather than emit uncompilable code.
        if (!Helpers.IsEffectivelyPublic(property.Type))
        {
            return false;
        }

        // A property typed with an obsolete-as-error type cannot be named in generated code at all.
        if (Helpers.IsUnusableType(property.Type))
        {
            return false;
        }

        return true;
    }

    bool CanGenerateITextAlignmentExtensions()
    {
        if (!Helpers.IsBaseImplementationOfInterface(mainSymbol, "ITextAlignment"))
        {
            return false;
        }

        return bindablePropertyNames.Any(name => name.Equals("VerticalTextAlignment", StringComparison.Ordinal))
            && bindablePropertyNames.Any(name => name.Equals("HorizontalTextAlignment", StringComparison.Ordinal));
    }

    bool IsEligibleField(IFieldSymbol field)
    {
        return field.DeclaredAccessibility == Accessibility.Public && !HasObsoleteAttribute(field);
    }

    /// <summary>
    /// Evaluates whether <c>self.Property = value;</c> can actually be written from the generated
    /// code, which lives in the CONSUMING assembly.
    ///
    /// Checking <see cref="Accessibility"/> against a hand-written list of "restricted" values is
    /// not enough: <c>protected internal</c> (<see cref="Accessibility.ProtectedOrInternal"/>) and
    /// <c>private protected</c> (<see cref="Accessibility.ProtectedAndInternal"/>) are neither of
    /// the three obvious values yet are both unreachable from another assembly — DrawnUi's
    /// <c>SkiaControl.IsMeasuring</c> (<c>{ get; protected internal set; }</c>) is exactly that
    /// case, and it produced CS0272 in every consuming project. Asking Roslyn settles all of them
    /// at once, including <c>internal</c> setters that ARE reachable thanks to
    /// <c>InternalsVisibleTo</c> when the target type lives in the compilation being generated for.
    /// </summary>
    /// <param name="property">The property to check.</param>
    /// <returns><see langword="true"/> when the setter can be invoked by the generated code.</returns>
    bool IsSetterUsable(IPropertySymbol property)
    {
        var setMethod = property.SetMethod;

        if (setMethod == null)
        {
            return false;
        }

        // `init` accessors are assignable only inside an object initializer, never through
        // `self.Property = value` in an extension method body (CS8852).
        if (setMethod.IsInitOnly)
        {
            return false;
        }

        return compilation.IsSymbolAccessibleWithin(setMethod, compilation.Assembly);
    }

    /// <summary>
    /// Resolves the element type for a read-only collection property, or <see langword="null"/>
    /// when no <c>Foo(params TItem[] items)</c> style fluent method can be generated for it.
    ///
    /// The shape heuristics below (implements IEnumerable, looks like a collection, is not an
    /// explicitly read-only collection) only establish that the property MIGHT be fillable. The
    /// decisive check is <see cref="HasAccessibleAdd"/>: the generated body is a
    /// <c>foreach (…) self.Property.Add(item);</c> loop, and plenty of BCL collection types satisfy
    /// every shape heuristic while having no callable <c>Add</c> at all — <c>Queue&lt;T&gt;</c> has
    /// <c>Enqueue</c>, and <c>LinkedList&lt;T&gt;</c> implements <c>ICollection&lt;T&gt;.Add</c>
    /// EXPLICITLY, so it is invisible to instance member lookup. Both appear on real controls
    /// (DrawnUi's <c>DrawnView.ExecuteAfterCreated</c> and <c>SkiaShell.NavigationStack*</c>) and
    /// both used to emit a loop that could not compile (CS1929).
    /// </summary>
    /// <param name="property">The read-only property to inspect.</param>
    /// <returns>The element type to generate against, or <see langword="null"/> to skip.</returns>
    ITypeSymbol? GetAddableElementType(IPropertySymbol property)
    {
        if (property.GetMethod == null || !compilation.IsSymbolAccessibleWithin(property.GetMethod, compilation.Assembly))
        {
            return null;
        }

        if (!HasCollectionShape(property.Type))
        {
            return null;
        }

        var elementType = ResolveElementType(property.Type);
        if (elementType == null || elementType.IsRefLikeType || !Helpers.IsEffectivelyPublic(elementType))
        {
            return null;
        }

        return HasAccessibleAdd(property.Type, elementType) ? elementType : null;
    }

    static bool HasCollectionShape(ITypeSymbol type)
    {
        var typeName = type.Name;

        if (typeName.Equals(nameof(String), StringComparison.OrdinalIgnoreCase))
            return false;

        var implementsEnumerable = type.AllInterfaces.Any(@interface => @interface.Name.IndexOf(nameof(IEnumerable), StringComparison.Ordinal) >= 0) ||
            typeName.IndexOf(nameof(IEnumerable), StringComparison.Ordinal) >= 0;
        if (!implementsEnumerable)
            return false;

        var implementsCollection = typeName.IndexOf(nameof(ICollection), StringComparison.Ordinal) >= 0 ||
            type.AllInterfaces.Any(@interface => @interface.Name.IndexOf(nameof(ICollection), StringComparison.Ordinal) >= 0);

        var implementsList = typeName.IndexOf(nameof(IList), StringComparison.Ordinal) >= 0 ||
            type.AllInterfaces.Any(@interface => @interface.Name.IndexOf(nameof(IList), StringComparison.Ordinal) >= 0);

        if (!implementsCollection && !implementsList)
            return false;

        var isReadOnlyList = typeName.IndexOf("IReadOnlyList", StringComparison.Ordinal) >= 0 ||
            type.AllInterfaces.Any(@interface => @interface.Name.IndexOf("IReadOnlyList", StringComparison.Ordinal) >= 0);

        var blockedPrefixes = new[] { "ReadOnlyObservableCollection", "ReadOnlyCollection", "ReadOnlyDictionary" };
        var isBlockedReadOnly = blockedPrefixes.Any(prefix => typeName.StartsWith(prefix, StringComparison.Ordinal)) ||
            (type.BaseType != null && blockedPrefixes.Any(prefix => type.BaseType.Name.StartsWith(prefix, StringComparison.Ordinal)));

        return (implementsCollection || !isReadOnlyList) && !isBlockedReadOnly;
    }

    /// <summary>
    /// Determines the item type a collection-shaped property holds: its own single type argument
    /// (<c>ObservableCollection&lt;Foo&gt;</c>, <c>IList&lt;Foo&gt;</c>) or, for a purpose-built
    /// subclass such as <c>class ItemCollection : ObservableCollection&lt;Foo&gt;</c>, the single
    /// type argument of the nearest generic base.
    /// </summary>
    /// <param name="type">The collection property type.</param>
    /// <returns>The element type, or <see langword="null"/> when it cannot be determined.</returns>
    static ITypeSymbol? ResolveElementType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return null;
        }

        if (namedType.TypeArguments.Length == 1)
        {
            return namedType.TypeArguments[0];
        }

        for (var baseType = namedType.BaseType; baseType != null; baseType = baseType.BaseType)
        {
            if (baseType.TypeArguments.Length == 1)
            {
                return baseType.TypeArguments[0];
            }
        }

        return null;
    }

    /// <summary>
    /// Evaluates whether <c>collection.Add(element)</c> binds to a real, callable instance method,
    /// following the same lookup rules the C# compiler applies to the generated call site: members
    /// declared on the type and its bases for a class, the interface plus its base interfaces for
    /// an interface. Explicit interface implementations are deliberately NOT matched — they carry a
    /// dotted metadata name and are unreachable without a cast, which is precisely the trap
    /// <c>LinkedList&lt;T&gt;</c> sets.
    /// </summary>
    /// <param name="collectionType">The property's collection type.</param>
    /// <param name="elementType">The item type the generated loop would pass to <c>Add</c>.</param>
    /// <returns><see langword="true"/> when an accessible one-argument <c>Add</c> accepts the element.</returns>
    bool HasAccessibleAdd(ITypeSymbol collectionType, ITypeSymbol elementType)
    {
        foreach (var lookupType in EnumerateMemberLookupTypes(collectionType))
        {
            foreach (var member in lookupType.GetMembers("Add"))
            {
                if (member is not IMethodSymbol method ||
                    method.IsStatic ||
                    method.MethodKind != MethodKind.Ordinary ||
                    method.IsGenericMethod ||
                    method.Parameters.Length != 1 ||
                    method.Parameters[0].RefKind != RefKind.None)
                {
                    continue;
                }

                if (HasObsoleteAttribute(method) || !compilation.IsSymbolAccessibleWithin(method, compilation.Assembly))
                {
                    continue;
                }

                if (compilation.HasImplicitConversion(elementType, method.Parameters[0].Type))
                {
                    return true;
                }
            }
        }

        return false;
    }

    static IEnumerable<ITypeSymbol> EnumerateMemberLookupTypes(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Interface)
        {
            yield return type;

            foreach (var baseInterface in type.AllInterfaces)
            {
                yield return baseInterface;
            }

            yield break;
        }

        for (var current = type as INamedTypeSymbol; current != null; current = current.BaseType)
        {
            yield return current;
        }
    }

    /// <summary>
    /// Classifies declared properties that collide by name with a base-class property.
    ///
    /// - Same property type and the base's fluent extensions exist (base is part of this
    ///   generation run, or it is a MAUI core type whose extensions ship inside
    ///   FmgLib.MauiMarkup): SKIP — the base's generic extension already serves this type, and
    ///   duplicating it would make every call ambiguous (CS0121). This covers the common
    ///   "redeclare the base BindableProperty for convenience" pattern (e.g. Syncfusion
    ///   SfButton.TextColor over ButtonBase.TextColor).
    /// - Same property type but no base extension exists: generate normally, WITHOUT a suffix —
    ///   the name matches the property and there is nothing to conflict with.
    /// - Different property type (a genuine `new` redefinition such as SfAvatarView.Background
    ///   changing Brush to Color): generate with the documented "New" suffix, because same-name
    ///   overloads differing only in the builder's generic argument would make lambda call
    ///   sites ambiguous and could silently target the wrong BindableProperty.
    /// </summary>
    /// <param name="properties">The declared public properties of the target type.</param>
    void ClassifyRedefinedProperties(IEnumerable<IPropertySymbol> properties)
    {
        redefinedProperties = new List<string>();
        skippedProperties = new HashSet<string>(StringComparer.Ordinal);

        foreach (var property in properties)
        {
            IPropertySymbol? baseProperty = null;
            INamedTypeSymbol? declaringBase = null;

            for (var baseType = mainSymbol.BaseType; baseType != null; baseType = baseType.BaseType)
            {
                baseProperty = baseType.GetMembers(property.Name)
                    .OfType<IPropertySymbol>()
                    .FirstOrDefault(candidate => candidate.DeclaredAccessibility == Accessibility.Public && !HasObsoleteAttribute(candidate));

                if (baseProperty != null)
                {
                    declaringBase = baseType;
                    break;
                }
            }

            if (baseProperty == null || declaringBase == null)
            {
                continue;
            }

            if (SymbolEqualityComparer.Default.Equals(property.Type, baseProperty.Type))
            {
                if (BaseGeneratesProperty(declaringBase, baseProperty))
                {
                    skippedProperties.Add(property.Name);
                }
            }
            else if (!property.IsOverride)
            {
                redefinedProperties.Add(property.Name);
            }
        }
    }

    /// <summary>
    /// Evaluates whether fluent extensions for the given base property will exist: the base type
    /// must have extensions (part of this generation run, or a MAUI core type shipped with the
    /// library) and the property itself must be generation-eligible there.
    /// </summary>
    /// <param name="declaringBase">The base type declaring the colliding property.</param>
    /// <param name="baseProperty">The colliding base property.</param>
    /// <returns><see langword="true"/> when the base's extension method covers this property.</returns>
    bool BaseGeneratesProperty(INamedTypeSymbol declaringBase, IPropertySymbol baseProperty)
    {
        var assemblyName = declaringBase.ContainingAssembly?.Name ?? string.Empty;
        var isCovered = assemblyName.StartsWith("Microsoft.Maui", StringComparison.Ordinal) ||
                        (generationSet != null && generationSet.Contains(declaringBase));

        if (!isCovered)
        {
            return false;
        }

        if (IsSetterUsable(baseProperty))
        {
            return true;
        }

        // A restricted setter still generates when a matching public BindableProperty field exists.
        return declaringBase.GetMembers(baseProperty.Name + "Property")
            .OfType<IFieldSymbol>()
            .Any(field => field.IsStatic && field.DeclaredAccessibility == Accessibility.Public);
    }

    bool HasObsoleteAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(attribute => attribute.AttributeClass?.Name is "ObsoleteAttribute" or "Obsolete");
    }

    bool HasEditorBrowsable(ISymbol symbol, INamedTypeSymbol? editorBrowsableAttribute)
    {
        return editorBrowsableAttribute != null && symbol.GetAttributes().Any(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, editorBrowsableAttribute));
    }

    void GenerateExtensionMethod(IPropertySymbol propertySymbol, bool isOnlyList = false)
    {
        var propertyName = propertySymbol.Name.Split(new[] { "." }, StringSplitOptions.None).Last();
        propertyName = propertyName.Equals("class", StringComparison.Ordinal) ? "@class" : propertyName;
        var info = new PropInfo
        {
            MainSymbolName = mainSymbol.ToQualifiedName(),
            BindablePropertyName = $"{mainSymbol.ToQualifiedName()}.{propertySymbol.Name}Property",
            PropertySymbol = propertySymbol,
            IsBindableProperty = bindablePropertyNames.Any(_ => _.Equals(propertySymbol.Name))
        };
        info.Build(redefinedProperties);

        if (!Helpers.NotGenerateList.Contains(info.propertyName))
        {
            if (isOnlyList)
            {
                // Same resolution the eligibility filter used, so the emitted element type is always
                // one that `self.Property.Add(item)` is known to accept.
                var elementType = GetAddableElementType(propertySymbol);

                if (elementType != null)
                    GenerateExtensionMethod_ContentProp_List(info, elementType.ToQualifiedName());
            }
            else
            {
                GenerateExtensionMethod_Value(info);

                if (info.IsBindableProperty)
                {
                    GenerateExtensionMethod_BindablePropertyBuilder(info);
                    GenerateExtensionMethod_Setters(info);
                    GenerateExtensionMethod_SettersBuilder(info);
                }

                if (info.propertyTypeName.Equals("global::Microsoft.Maui.Controls.DataTemplate"))
                    GenerateExtensionMethod_DataTemplate(info);

                if (isVisualElement)
                {
                    if (info.propertyTypeName.Equals("double"))
                        GenerateExtensionMethod_AnimateTo(info, "DoubleTransform");

                    if (info.propertyTypeName.Equals("global::Microsoft.Maui.Graphics.Color"))
                        GenerateExtensionMethod_AnimateTo(info, "ColorTransform");
                }
            }

            isGeneratedExtension = true;
        }
    }

    void GenerateAttachedExtensionMethod(AttachedModel parameter)
    {
        var info = new AttachedFieldInfo
        {
            MainSymbol = mainSymbol,
            BindablePropertyName = $"{mainSymbol.ToQualifiedName()}.{parameter.PropertyName}",
            ReturnTypeName = parameter.ReturnTypeName,
            DeclaringTypeName = parameter.DeclaringTypeName,
            PropertyName = parameter.PropertyName
        };
        info.Build();

        if (!Helpers.NotGenerateList.Contains(info.propertyName))
        {
            GenerateExtensionMethod_Value(info);
            GenerateExtensionMethod_BindablePropertyBuilder(info);
            GenerateExtensionMethod_Setters(info);
            GenerateExtensionMethod_SettersBuilder(info);

            isGeneratedExtension = true;
        }
    }
}
