using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace FmgLib.MauiMarkup.Generator.Extensions;

/// <summary>
/// Builds the generated extension methods for a given MAUI control or attached property.
/// </summary>
public sealed partial class ExtensionGenerator
{
    readonly Compilation compilation;
    readonly CancellationToken cancellationToken;
    readonly INamedTypeSymbol mainSymbol;
    readonly bool isVisualElement;
    bool isGeneratedExtension = false;
    readonly AttachedModel? attachedModel;
    readonly ISet<INamedTypeSymbol>? generationSet;
    List<string> bindablePropertyNames = new();
    List<string> redefinedProperties = new();
    HashSet<string> skippedProperties = new();

    StringBuilder builder = new();

    public ExtensionGenerator(Compilation compilation, INamedTypeSymbol symbol, CancellationToken cancellationToken)
        : this(compilation, symbol, generationSet: null, cancellationToken)
    {
    }

    public ExtensionGenerator(Compilation compilation, INamedTypeSymbol symbol, ISet<INamedTypeSymbol>? generationSet, CancellationToken cancellationToken)
    {
        this.compilation = compilation;
        this.mainSymbol = symbol;
        this.cancellationToken = cancellationToken;
        this.generationSet = generationSet;
        isVisualElement = Helpers.IsVisualElement(mainSymbol);
    }

    public ExtensionGenerator(Compilation compilation, AttachedModel attachedModel, CancellationToken cancellationToken)
    {
        this.compilation = compilation;
        this.mainSymbol = attachedModel.MainSymbol;
        this.cancellationToken = cancellationToken;
        isVisualElement = Helpers.IsVisualElement(mainSymbol);
        this.attachedModel = attachedModel;
    }

    public (string, string, bool) Build()
    {
        builder.Clear();
        builder.AppendLine("//");
        builder.AppendLine("// <auto-generated-fmglib-mauimarkup-generator />");
        builder.AppendLine("//");
        builder.AppendLine();

        GenerateExtensionNameSpace();

        builder.AppendLine();

        return ($"{mainSymbol.ContainingNamespace.ToDisplayString()}.{Helpers.GetNormalizedFileName(mainSymbol)}{(attachedModel != null ? "Attached" : "")}", builder.ToString(), isGeneratedExtension);
    }

    void GenerateExtensionNameSpace()
    {
        var className = $"{Helpers.GetNormalizedClassName(mainSymbol)}{(attachedModel != null ? "Attached" : "")}Extension";

        builder.Append($@"
namespace FmgLib.MauiMarkup;

public static partial class {className}
{{");

        GenerateClassExtensionBody();

        builder.AppendLine($@"
}}
");
    }

    void GenerateClassExtensionBody()
    {
        cancellationToken.ThrowIfCancellationRequested();

        var editorBrowsableAttribute = compilation.FindNamedType("System.ComponentModel.EditorBrowsableAttribute");
        var bindablePropertyType = compilation.FindNamedType("Microsoft.Maui.Controls.BindableProperty");
        var members = mainSymbol
            .GetMembers()
            .Where(member => SymbolEqualityComparer.Default.Equals(member.ContainingType, mainSymbol))
            .ToArray();

        var propertiesMap = members
            .OfType<IPropertySymbol>()
            .Where(IsEligibleProperty)
            .OrderBy(property => property.Name, StringComparer.Ordinal)
            .ToList();

        ClassifyRedefinedProperties(propertiesMap);

        var fieldsMap = members
            .OfType<IFieldSymbol>()
            .Where(IsEligibleField)
            .ToList();

        bindablePropertyNames = fieldsMap
            .Where(field => field.IsStatic &&
                ((bindablePropertyType != null && SymbolEqualityComparer.Default.Equals(field.Type, bindablePropertyType)) ||
                 field.Type.GetFullyQualifiedName().Equals("Microsoft.Maui.Controls.BindableProperty", StringComparison.Ordinal)))
            .Select(field => field.Name.Replace("PropertyKey", string.Empty).Replace("Property", string.Empty))
            .ToList();

        var properties = propertiesMap
            .Where(property => !skippedProperties.Contains(property.Name))
            .Where(property => (!property.IsReadOnly && !IsSetterRestricted(property)) || bindablePropertyNames.Any(name => name.Equals(property.Name, StringComparison.Ordinal)))
            .ToList();

        var readOnlyListProperties = propertiesMap
            .Where(property => !skippedProperties.Contains(property.Name))
            .Where(property => property.IsReadOnly &&
                !bindablePropertyNames.Any(name => name.Equals(property.Name, StringComparison.InvariantCultureIgnoreCase)) &&
                IsSupportedCollection(property))
            .ToList();

        var events = members
           .OfType<IEventSymbol>()
           .Where(@event => @event.DeclaredAccessibility == Accessibility.Public)
           .Where(@event => @event.Name.IndexOf('.') < 0)
           .Where(@event => !HasEditorBrowsable(@event, editorBrowsableAttribute))
           .Where(@event => !HasObsoleteAttribute(@event))
           // Same reasoning as static properties: `self.Event += handler` on a static event is a
           // compile error (CS0176), and a static event is process-wide, not per-instance, state.
           .Where(@event => !@event.IsStatic)
           // The generated handler parameter/lambda action type must itself be public, or every
           // consumer outside this assembly fails to compile against the generated method.
           .Where(@event => Helpers.IsEffectivelyPublic(@event.Type))
           .GroupBy(@event => @event.Name, StringComparer.OrdinalIgnoreCase)
           .Select(group => group.First())
           .OrderBy(@event => @event.Name, StringComparer.Ordinal)
           .ToArray();

        if (attachedModel == null)
        {
            foreach (var prop in readOnlyListProperties)
            {
                cancellationToken.ThrowIfCancellationRequested();
                GenerateExtensionMethod(prop, true);
            }

            foreach (var prop in properties)
            {
                cancellationToken.ThrowIfCancellationRequested();
                GenerateExtensionMethod(prop);
            }

            foreach (var @event in events)
            {
                cancellationToken.ThrowIfCancellationRequested();
                GenerateEventMethod(@event);
            }

            if (CanGenerateITextAlignmentExtensions())
                GenerateExtensionMethods_ITextAlignment(mainSymbol);
        }
        else
        {
            GenerateAttachedExtensionMethod(attachedModel!);
        }
    }

    bool IsEligibleProperty(IPropertySymbol property)
    {
        if (property.DeclaredAccessibility != Accessibility.Public || HasObsoleteAttribute(property))
        {
            return false;
        }

        // Static properties are type-level configuration (e.g. a shared default), not per-instance
        // state — an instance-fluent `new Foo().Bar(value)` extension would silently write to the
        // TYPE, not to `self`, which is misleading API design and, worse, several of the generated
        // shapes (notably Animate…To) hardcode an instance access and would emit `self.Bar = value`
        // for a static member, which fails to compile (CS0176). Skipping statics entirely avoids the
        // whole class of bugs rather than special-casing every generation shape. Setting a static
        // config knob remains a single plain C# statement (`SomeControl.Bar = value;`) that needs no
        // fluent wrapper.
        if (property.IsStatic)
        {
            return false;
        }

        // Ref-returning properties (`ref readonly T Foo => ref field;`) cannot be targeted by a
        // normal `self.Foo = value` assignment.
        if (property.ReturnsByRef || property.ReturnsByRefReadonly)
        {
            return false;
        }

        // A `ref struct` (e.g. Span<T>) property type cannot be used as a generic method parameter
        // or captured in a lambda/local, both of which the generated overloads require.
        if (property.Type.IsRefLikeType)
        {
            return false;
        }

        // A public property whose type (or a generic type argument / array element type) is not
        // itself public cannot appear in a public method signature without breaking every caller
        // outside this assembly (CS0053-class errors). This is an occasional, deliberate or
        // accidental pattern in third-party libraries; skip rather than emit uncompilable code.
        if (!Helpers.IsEffectivelyPublic(property.Type))
        {
            return false;
        }

        return true;
    }

    bool CanGenerateITextAlignmentExtensions()
    {
        if (!Helpers.IsBaseImplementationOfInterface(mainSymbol, "ITextAlignment"))
        {
            return false;
        }

        return bindablePropertyNames.Any(name => name.Equals("VerticalTextAlignment", StringComparison.Ordinal))
            && bindablePropertyNames.Any(name => name.Equals("HorizontalTextAlignment", StringComparison.Ordinal));
    }

    bool IsEligibleField(IFieldSymbol field)
    {
        return field.DeclaredAccessibility == Accessibility.Public && !HasObsoleteAttribute(field);
    }

    static bool IsSetterRestricted(IPropertySymbol property)
    {
        return property.SetMethod == null || property.SetMethod.DeclaredAccessibility is Accessibility.Protected or Accessibility.Private or Accessibility.Internal;
    }

    bool IsSupportedCollection(IPropertySymbol property)
    {
        var type = property.Type;
        var typeName = type.Name;

        if (typeName.Equals(nameof(String), StringComparison.OrdinalIgnoreCase))
            return false;

        var implementsEnumerable = type.AllInterfaces.Any(@interface => @interface.Name.IndexOf(nameof(IEnumerable), StringComparison.Ordinal) >= 0) ||
            typeName.IndexOf(nameof(IEnumerable), StringComparison.Ordinal) >= 0;
        if (!implementsEnumerable)
            return false;

        var implementsCollection = typeName.IndexOf(nameof(ICollection), StringComparison.Ordinal) >= 0 ||
            type.AllInterfaces.Any(@interface => @interface.Name.IndexOf(nameof(ICollection), StringComparison.Ordinal) >= 0);

        var implementsList = typeName.IndexOf(nameof(IList), StringComparison.Ordinal) >= 0 ||
            type.AllInterfaces.Any(@interface => @interface.Name.IndexOf(nameof(IList), StringComparison.Ordinal) >= 0);

        if (!implementsCollection && !implementsList)
            return false;

        var isReadOnlyList = typeName.IndexOf("IReadOnlyList", StringComparison.Ordinal) >= 0 ||
            type.AllInterfaces.Any(@interface => @interface.Name.IndexOf("IReadOnlyList", StringComparison.Ordinal) >= 0);

        var blockedPrefixes = new[] { "ReadOnlyObservableCollection", "ReadOnlyCollection", "ReadOnlyDictionary" };
        var isBlockedReadOnly = blockedPrefixes.Any(prefix => typeName.StartsWith(prefix, StringComparison.Ordinal)) ||
            (type.BaseType != null && blockedPrefixes.Any(prefix => type.BaseType.Name.StartsWith(prefix, StringComparison.Ordinal)));

        return (implementsCollection || !isReadOnlyList) && !isBlockedReadOnly;
    }

    /// <summary>
    /// Classifies declared properties that collide by name with a base-class property.
    ///
    /// - Same property type and the base's fluent extensions exist (base is part of this
    ///   generation run, or it is a MAUI core type whose extensions ship inside
    ///   FmgLib.MauiMarkup): SKIP — the base's generic extension already serves this type, and
    ///   duplicating it would make every call ambiguous (CS0121). This covers the common
    ///   "redeclare the base BindableProperty for convenience" pattern (e.g. Syncfusion
    ///   SfButton.TextColor over ButtonBase.TextColor).
    /// - Same property type but no base extension exists: generate normally, WITHOUT a suffix —
    ///   the name matches the property and there is nothing to conflict with.
    /// - Different property type (a genuine `new` redefinition such as SfAvatarView.Background
    ///   changing Brush to Color): generate with the documented "New" suffix, because same-name
    ///   overloads differing only in the builder's generic argument would make lambda call
    ///   sites ambiguous and could silently target the wrong BindableProperty.
    /// </summary>
    /// <param name="properties">The declared public properties of the target type.</param>
    void ClassifyRedefinedProperties(IEnumerable<IPropertySymbol> properties)
    {
        redefinedProperties = new List<string>();
        skippedProperties = new HashSet<string>(StringComparer.Ordinal);

        foreach (var property in properties)
        {
            IPropertySymbol? baseProperty = null;
            INamedTypeSymbol? declaringBase = null;

            for (var baseType = mainSymbol.BaseType; baseType != null; baseType = baseType.BaseType)
            {
                baseProperty = baseType.GetMembers(property.Name)
                    .OfType<IPropertySymbol>()
                    .FirstOrDefault(candidate => candidate.DeclaredAccessibility == Accessibility.Public && !HasObsoleteAttribute(candidate));

                if (baseProperty != null)
                {
                    declaringBase = baseType;
                    break;
                }
            }

            if (baseProperty == null || declaringBase == null)
            {
                continue;
            }

            if (SymbolEqualityComparer.Default.Equals(property.Type, baseProperty.Type))
            {
                if (BaseGeneratesProperty(declaringBase, baseProperty))
                {
                    skippedProperties.Add(property.Name);
                }
            }
            else if (!property.IsOverride)
            {
                redefinedProperties.Add(property.Name);
            }
        }
    }

    /// <summary>
    /// Evaluates whether fluent extensions for the given base property will exist: the base type
    /// must have extensions (part of this generation run, or a MAUI core type shipped with the
    /// library) and the property itself must be generation-eligible there.
    /// </summary>
    /// <param name="declaringBase">The base type declaring the colliding property.</param>
    /// <param name="baseProperty">The colliding base property.</param>
    /// <returns><see langword="true"/> when the base's extension method covers this property.</returns>
    bool BaseGeneratesProperty(INamedTypeSymbol declaringBase, IPropertySymbol baseProperty)
    {
        var assemblyName = declaringBase.ContainingAssembly?.Name ?? string.Empty;
        var isCovered = assemblyName.StartsWith("Microsoft.Maui", StringComparison.Ordinal) ||
                        (generationSet != null && generationSet.Contains(declaringBase));

        if (!isCovered)
        {
            return false;
        }

        if (!baseProperty.IsReadOnly && !IsSetterRestricted(baseProperty))
        {
            return true;
        }

        // A restricted setter still generates when a matching public BindableProperty field exists.
        return declaringBase.GetMembers(baseProperty.Name + "Property")
            .OfType<IFieldSymbol>()
            .Any(field => field.IsStatic && field.DeclaredAccessibility == Accessibility.Public);
    }

    bool HasObsoleteAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(attribute => attribute.AttributeClass?.Name is "ObsoleteAttribute" or "Obsolete");
    }

    bool HasEditorBrowsable(ISymbol symbol, INamedTypeSymbol? editorBrowsableAttribute)
    {
        return editorBrowsableAttribute != null && symbol.GetAttributes().Any(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, editorBrowsableAttribute));
    }

    void GenerateExtensionMethod(IPropertySymbol propertySymbol, bool isOnlyList = false)
    {
        var propertyName = propertySymbol.Name.Split(new[] { "." }, StringSplitOptions.None).Last();
        propertyName = propertyName.Equals("class", StringComparison.Ordinal) ? "@class" : propertyName;
        var info = new PropInfo
        {
            MainSymbolName = mainSymbol.ToDisplayString(),
            BindablePropertyName = $"{mainSymbol.ToDisplayString()}.{propertySymbol.Name}Property",
            PropertySymbol = propertySymbol,
            IsBindableProperty = bindablePropertyNames.Any(_ => _.Equals(propertySymbol.Name))
        };
        info.Build(redefinedProperties);

        if (!Helpers.NotGenerateList.Contains(info.propertyName))
        {
            if (isOnlyList)
            {
                string typeName = "";
                if (propertySymbol.IsReadOnly && propertySymbol.Type is INamedTypeSymbol namedType && namedType.TypeArguments.Length == 1)
                    typeName = namedType.TypeArguments[0].ToDisplayString();

                else if (propertySymbol.IsReadOnly && propertySymbol.Type is INamedTypeSymbol namedListType &&
                            namedListType.AllInterfaces.Any(e => e.Name == nameof(IEnumerable)) &&
                            namedListType.BaseType?.TypeArguments.Length == 1)
                    typeName = namedListType.BaseType!.TypeArguments[0].ToDisplayString();

                if (!string.IsNullOrEmpty(typeName))
                    GenerateExtensionMethod_ContentProp_List(info, typeName);
            }
            else
            {
                GenerateExtensionMethod_Value(info);

                if (info.IsBindableProperty)
                {
                    GenerateExtensionMethod_BindablePropertyBuilder(info);
                    GenerateExtensionMethod_Setters(info);
                    GenerateExtensionMethod_SettersBuilder(info);
                }

                if (info.propertyTypeName.Equals("Microsoft.Maui.Controls.DataTemplate"))
                    GenerateExtensionMethod_DataTemplate(info);

                if (isVisualElement)
                {
                    if (info.propertyTypeName.Equals("double"))
                        GenerateExtensionMethod_AnimateTo(info, "DoubleTransform");

                    if (info.propertyTypeName.Equals("Microsoft.Maui.Graphics.Color"))
                        GenerateExtensionMethod_AnimateTo(info, "ColorTransform");
                }
            }

            isGeneratedExtension = true;
        }
    }

    void GenerateAttachedExtensionMethod(AttachedModel parameter)
    {
        var info = new AttachedFieldInfo
        {
            MainSymbol = mainSymbol,
            BindablePropertyName = $"{mainSymbol.ToDisplayString()}.{parameter.PropertyName}",
            ReturnTypeName = parameter.ReturnTypeName,
            DeclaringTypeName = parameter.DeclaringTypeName,
            PropertyName = parameter.PropertyName
        };
        info.Build();

        if (!Helpers.NotGenerateList.Contains(info.propertyName))
        {
            GenerateExtensionMethod_Value(info);
            GenerateExtensionMethod_BindablePropertyBuilder(info);
            GenerateExtensionMethod_Setters(info);
            GenerateExtensionMethod_SettersBuilder(info);

            isGeneratedExtension = true;
        }
    }
}
